version: '3.1'

services:

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  adminer:
    image: adminer
    ports:
      - 8080:8080

  lychee:
    build: .
    ports:
      - 81:80
    links:
      - mysql
